#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'mytalker','console_scripts','talker'
__requires__ = 'mytalker'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('mytalker', 'console_scripts', 'talker')()
    )
